'use client'; /* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {readAgreement,readVault,requireAddress} from '../lib/genlayer/contracts';import {submitAndConfirm,TxState} from '../lib/genlayer/transaction';import {useWallet} from '../lib/wallet/provider';import {verifyEvidence} from '../lib/hash';import {validateEvidenceUrl} from '../lib/evidence';
type Action='accept'|'fund'|'return'|'inspect'|'receipt';const wait=async(ms:number)=>new Promise(r=>setTimeout(r,ms));
export default function LiveRoute({id,action}:{id:string;action:Action}){
 const wallet=useWallet();const [now]=useState(()=>Math.floor(Date.now()/1000));const [agreement,setAgreement]=useState<any>();const [vault,setVault]=useState<any>();const [value,setValue]=useState('');const [hash,setHash]=useState('');const [local,setLocal]=useState<File>();const [match,setMatch]=useState<boolean>();const [tx,setTx]=useState<TxState>({phase:'IDLE'});const [error,setError]=useState('');
 const agreementAddress=useMemo(()=>{try{return requireAddress(id,'Agreement')}catch{return ''}},[id]);const vaultAddress=(()=>{try{return agreement?.vault?requireAddress(String(agreement.vault),'Vault'):''}catch{return ''}})();
 const read=async()=>{if(!agreementAddress)return {a:null,v:null};const a=await readAgreement(agreementAddress);const v=a?.vault?await readVault(requireAddress(String(a.vault),'Vault')):null;setAgreement(a);setVault(v);return {a,v}};useEffect(()=>{void read().catch(e=>setError(String(e)));},[agreementAddress]);
 const expected=async(before:any)=>{for(let i=0;i<12;i++){const {a,v}=await read();if(action==='accept'&&a?.status==='BASELINE_ACCEPTED')return true;if(action==='fund'&&a?.status==='FUNDED'&&v?.credited===BigInt(a.deposit))return true;if(action==='return'&&a?.status==='RETURN_SUBMITTED'&&a.return_url===value&&a.return_hash===hash)return true;if(action==='inspect'&&(a?.status==='DECIDED'||(a?.status==='RETURN_SUBMITTED'&&BigInt(a.reinspection_count)>BigInt(before?.reinspection_count||0))))return true;await wait(5000)}return false};
 const verifyReturn=async()=>{try{setError('');if(!local)throw Error('Select the local return image first.');if(!validateEvidenceUrl(value))throw Error('Use a safe HTTPS return URL.');const result=await verifyEvidence(local,value);setHash(result.localHash);setMatch(result.match);if(!result.match)throw Error('Local and remote return hashes do not match.')}catch(e){setMatch(false);setError(e instanceof Error?e.message:String(e))}};
 const run=async()=>{try{setError('');if(!wallet?.client||!wallet.account)throw Error('Connect a Studionet wallet first.');if(!wallet.onStudionet)throw Error('Switch wallet to Studionet 61999.');if(!agreementAddress)throw Error('Enter a valid Agreement address.');const before=agreement;let call:any;if(action==='accept')call={address:agreementAddress,functionName:'accept_baseline',args:[value]};else if(action==='fund')call={address:vaultAddress,functionName:'deposit',args:[],value:BigInt(agreement.deposit)};else if(action==='return'){if(match!==true)throw Error('Verify the local and remote return images first.');call={address:agreementAddress,functionName:'submit_return',args:[value,hash]}}else if(action==='inspect')call={address:agreementAddress,functionName:'inspect',args:[]};else throw Error('This page is read-only.');await submitAndConfirm(wallet.client,call,()=>expected(before),setTx)}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const expire=async()=>{const before=agreement;await submitAndConfirm(wallet.client,{address:agreementAddress,functionName:'expire',args:[]},async()=>{for(let i=0;i<12;i++){const {a}=await read();if(a?.status==='CANCELLED'||a?.status==='DECIDED')return a?.status!==before?.status;await wait(5000)}return false},setTx)};
 const title={accept:'Accept the exact passport.',fund:'Deposit the exact security.',return:'Pin the return.',inspect:'Compare the exact pair.',receipt:'Settlement receipt.'}[action];
 return <main className="wrap"><nav className="nav"><Link className="wordmark" href={`/a/${id}`}>WEARSEAL<span className="orange">/</span></Link><span className="mono">{action.toUpperCase()} · STUDIONET 61999</span></nav><section style={{maxWidth:760,margin:'60px auto'}}><div className="mono orange">AUTHORITATIVE CONTRACT STATE</div><h1>{title}</h1>{error&&<p className="orange">{error}</p>}<div className="plate card mono">{agreement?<>STATUS: {agreement.status}<br/>DEADLINE: {new Date(Number(agreement.deadline)*1000).toISOString()}<br/>OWNER: {agreement.owner}<br/>RENTER: {agreement.renter}<br/>DEPOSIT: {String(agreement.deposit)}<br/>VERDICT: {agreement.verdict||'—'}{vault&&<><br/>VAULT: {vault.settled?'SETTLED':String(vault.credited)}<br/>OWNER CLAIM: {String(vault.owner_claim||0)}<br/>RENTER CLAIM: {String(vault.renter_claim||0)}</>}</>: 'READING LIVE STATE…'}</div>{action==='accept'&&<input className="plate" placeholder="0x + 64-character definition hash" value={value} onChange={e=>setValue(e.target.value)}/>} {action==='return'&&<><label className="mono">LOCAL RETURN IMAGE<input className="plate" type="file" accept="image/*" onChange={e=>{setLocal(e.target.files?.[0]);setMatch(undefined);setHash('')}}/></label><input className="plate" placeholder="Public HTTPS return URL" value={value} onChange={e=>setValue(e.target.value)}/><button className="button" onClick={verifyReturn}>VERIFY RETURN IMAGE</button>{hash&&<p className="mono">RETURN HASH: {hash} · {match?'MATCH':'MISMATCH'}</p>}</>} {action!=='receipt'&&<button className="button" onClick={run} disabled={tx.phase==='AWAITING_SIGNATURE'||tx.phase==='CONSENSUS_RUNNING'}>{tx.phase==='IDLE'?'EXECUTE + CONFIRM':tx.phase}</button>}{agreement&&Number(agreement.deadline)<now&&!['SETTLED','CANCELLED'].includes(agreement.status)&&<button className="button" onClick={expire}>EXPIRE AGREEMENT</button>}{tx.hash&&<p className="mono">TX: {tx.hash}</p>}<p><Link href={`/a/${id}`}>← BACK TO PASSPORT</Link></p></section></main>;
}
