'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useWallet} from '../../lib/wallet/provider';
import {fetchAndHash} from '../../lib/hash';

const agreementSource='https://raw.githubusercontent.com/Bibidee/wearseal/main/contracts/wearseal_agreement.py';
const vaultSource='https://raw.githubusercontent.com/Bibidee/wearseal/main/contracts/wearseal_vault.py';
const checkoutDefault='https://raw.githubusercontent.com/Bibidee/wearseal/main/public/fixtures/checkout.png';
export default function New(){
 const wallet=useWallet(); const [renter,setRenter]=useState('');const [label,setLabel]=useState('');const [url,setUrl]=useState(checkoutDefault);const [imageHash,setImageHash]=useState('');const [rubric,setRubric]=useState('Normal wear is acceptable; scratches are minor; cracks or missing parts are material.');const [state,setState]=useState('IDLE');const [error,setError]=useState('');const [passport,setPassport]=useState('');
 const publish=async()=>{try{setError('');if(!wallet?.client||!wallet.account)throw Error('Connect a wallet first.');if(!wallet.onStudionet)throw Error('Switch wallet to Studionet 61999.');if(!/^0x[a-fA-F0-9]{40}$/.test(renter))throw Error('Enter the renter address.');if(!label||!imageHash)throw Error('Item label and checkout hash are required.');setState('FETCHING SOURCES');const [aCode,vCode]=await Promise.all([fetch(agreementSource).then(r=>r.text()),fetch(vaultSource).then(r=>r.text())]);setState('DEPLOYING AGREEMENT');const aHash=await wallet.client.deployContract({code:aCode,args:[wallet.account,renter,label,'serial-hash',rubric,url,imageHash,1000000000000000n,1500,10000,9999999999n]});const ar=await wallet.client.waitForTransactionReceipt({hash:aHash,status:'FINALIZED',retries:220,interval:5000});if(ar.consensus_data?.leader_receipt?.[0]?.execution_result!=='SUCCESS')throw Error('Agreement deployment failed.');const agreement=ar.data?.contract_address;if(!agreement)throw Error('Agreement address was not returned.');setState('DEPLOYING VAULT');const vHash=await wallet.client.deployContract({code:vCode,args:[agreement]});const vr=await wallet.client.waitForTransactionReceipt({hash:vHash,status:'FINALIZED',retries:220,interval:5000});if(vr.consensus_data?.leader_receipt?.[0]?.execution_result!=='SUCCESS')throw Error('Vault deployment failed.');const vault=vr.data?.contract_address;if(!vault)throw Error('Vault address was not returned.');setState('BINDING');const bHash=await wallet.client.writeContract({address:agreement,functionName:'bind_vault',args:[vault]});const br=await wallet.client.waitForTransactionReceipt({hash:bHash,status:'FINALIZED',retries:220,interval:5000});if(br.consensus_data?.leader_receipt?.[0]?.execution_result!=='SUCCESS')throw Error('Binding failed.');setPassport(agreement);setState('READY');}catch(e){setError(e instanceof Error?e.message:String(e));setState('ERROR')}};
 return <main className="wrap"><nav className="nav"><Link className="wordmark" href="/">WEARSEAL<span className="orange">/</span></Link><span className="mono">NEW PASSPORT · STUDIONET 61999</span></nav><section style={{maxWidth:760,margin:'60px auto'}}><div className="mono orange">LIVE DEPLOYMENT</div><h1>Make the baseline explicit.</h1><p>Deploys the Agreement and Vault from the committed source, binds them, waits for finality, and links to the authoritative passport.</p><input className="plate" placeholder="Renter address" value={renter} onChange={e=>setRenter(e.target.value)}/><input className="plate" placeholder="Item label" value={label} onChange={e=>setLabel(e.target.value)}/><input className="plate" placeholder="Checkout HTTPS URL" value={url} onChange={e=>setUrl(e.target.value)}/><input className="plate" placeholder="0x + checkout SHA-256" value={imageHash} onChange={e=>setImageHash(e.target.value)} onBlur={async()=>{if(url)try{setImageHash(await fetchAndHash(url))}catch{}}}/><textarea className="plate" placeholder="Condition rubric" value={rubric} onChange={e=>setRubric(e.target.value)}/><button className="button" onClick={publish} disabled={state!=='IDLE'&&state!=='ERROR'}>{state==='IDLE'?'DEPLOY + BIND →':state}</button>{error&&<p className="orange">{error}</p>}{passport&&<p className="mono"><Link href={`/a/${passport}`}>OPEN LIVE PASSPORT →</Link></p>}</section></main>;
}
